version: '3.8'

services:
  db-carrito:
    image: mysql:8.0
    container_name: mysql-carrito
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carrito_db
    ports:
      - "3307:3306"
    volumes:
      - db_carrito_data:/var/lib/mysql

volumes:
  db_carrito_data: